language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
  
env:
  - MAVEN_OPTS=Xmx1024m
  
os:
  - linux

branches:
  only:
    - master

before_install:
  echo "127.0.0.1 "hostname | sudo tee /etc/hosts

install: mvn clean package

