language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

branches:
  only:
    - master

install: mvn clean package

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
