language: java
jdk:
  - oraclejdk7
  - openjdk7

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
  - which thrift 
  
install: mvn clean package
