language: java
jdk:
  - oraclejdk7
  - openjdk7

branches:
  only:
    - master

install: mvn clean deploy -DaltDeploymentRepository=central::default::https://oss.sonatype.org/content/repositories/snapshots
