jobs:
  - job: linux_arm64
    displayName: "on linux-arm64"
    pool:
      name: "arm64"
      vmImage:
      demands:
        - Agent.Name -equals arm64-$(Build.BuildId)
    dependsOn:
      - StartArmAgent
    strategy:
      matrix:
        griffin:
          includeTests: "**/griffin/**"
          testset: "all"
          javadoc_step: ""
          javadoc_profile: ""
          jdk: "1.11"
          os: Linux
        other:
          excludeTests: "**/griffin/**"
          testset: "all"
          javadoc_step: ""
          javadoc_profile: ""
          jdk: "1.11"
          os: Linux
    timeoutInMinutes: 60
    condition: eq(variables['System.PullRequest.IsFork'], 'false')
    variables:
      SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED']]
      CODE_COVERAGE_TOOL_OPTION: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.CODE_COVERAGE_TOOL_OPTION']]
      ARCHIVED_CRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
    steps:
      - template: steps.yml
