trigger:
  tags:
    include:
      - '*patch*'

jobs:
  - job: RunOn
    displayName: "Build and push docker"

    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"

    timeoutInMinutes: 60

    steps:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: quest_docker_hub

      - bash: |
          export tag_name=$(git describe --tags) && docker buildx build --build-arg tag_name --push --platform linux/amd64 --tag questdb/$tag_name .
        displayName: Build And Push
